[package]
edition = "2024"
name = "pg-constraint-macro"
publish = false
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "1"
sqlx = { version = "0.8.6", default-features = false, features = [
  "runtime-tokio",
  "postgres",
  "macros",
] }
strsim = "0.11"
syn = "2"
tokio = { version = "1.49", default-features = false, features = ["rt"] }

[lints]
workspace = true
